//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormWorks.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonal
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
